import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from 'styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next CMS Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles["card"]}>
          <h3>Options</h3>
          <Link href="/sample" passHref>
              <a>
                View
              </a>
          </Link>
          <Link href="/sample/edit" passHref>
              <a>
                Edit
              </a>
          </Link>
        </div>
      </main>

     
    </div>
  )
}

export default Home
